#ifndef DIO_Config_H_
#define DIO_Config_H_

/*_Here you can configure inital direction and values for the pins_*/
/*Initial Direction*/
#define PIN_INPUT 0
#define PIN_OUTPUT 1

#define PA0_INITIAL_DIR PIN_OUTPUT
#define PA1_INITIAL_DIR PIN_OUTPUT
#define PA2_INITIAL_DIR PIN_OUTPUT
#define PA3_INITIAL_DIR PIN_OUTPUT
#define PA4_INITIAL_DIR PIN_INPUT
#define PA5_INITIAL_DIR PIN_INPUT
#define PA6_INITIAL_DIR PIN_INPUT
#define PA7_INITIAL_DIR PIN_INPUT

#define PB0_INITIAL_DIR PIN_OUTPUT
#define PB1_INITIAL_DIR PIN_OUTPUT
#define PB2_INITIAL_DIR PIN_OUTPUT
#define PB3_INITIAL_DIR PIN_OUTPUT
#define PB4_INITIAL_DIR PIN_OUTPUT
#define PB5_INITIAL_DIR PIN_OUTPUT
#define PB6_INITIAL_DIR PIN_OUTPUT
#define PB7_INITIAL_DIR PIN_OUTPUT

#define PC0_INITIAL_DIR PIN_INPUT
#define PC1_INITIAL_DIR PIN_INPUT
#define PC2_INITIAL_DIR PIN_INPUT
#define PC3_INITIAL_DIR PIN_INPUT
#define PC4_INITIAL_DIR PIN_INPUT
#define PC5_INITIAL_DIR PIN_INPUT
#define PC6_INITIAL_DIR PIN_INPUT
#define PC7_INITIAL_DIR PIN_INPUT

#define PD0_INITIAL_DIR PIN_INPUT
#define PD1_INITIAL_DIR PIN_OUTPUT
#define PD2_INITIAL_DIR PIN_OUTPUT
#define PD3_INITIAL_DIR PIN_OUTPUT
#define PD4_INITIAL_DIR PIN_INPUT
#define PD5_INITIAL_DIR PIN_OUTPUT
#define PD6_INITIAL_DIR PIN_INPUT
#define PD7_INITIAL_DIR PIN_INPUT

/***************************************/
/*Initial Value*/
#define PIN_RESET 0
#define PIN_SET 1              /*high*/

#define PIN_FLOATING 0
#define PIN_PULL_UP 1 
/*if direction is output use PIN_RESET or PIN_SET*/
/*if direction is Input use PIN_FLOATING or PIN_PULL_UP*/


#define PA0_INITIAL_VALUE PIN_RESET
#define PA1_INITIAL_VALUE PIN_RESET
#define PA2_INITIAL_VALUE PIN_RESET
#define PA3_INITIAL_VALUE PIN_RESET
#define PA4_INITIAL_VALUE PIN_FLOATING
#define PA5_INITIAL_VALUE PIN_FLOATING
#define PA6_INITIAL_VALUE PIN_FLOATING
#define PA7_INITIAL_VALUE PIN_FLOATING

#define PB0_INITIAL_VALUE PIN_FLOATING
#define PB1_INITIAL_VALUE PIN_FLOATING
#define PB2_INITIAL_VALUE PIN_FLOATING
#define PB3_INITIAL_VALUE PIN_FLOATING
#define PB4_INITIAL_VALUE PIN_FLOATING
#define PB5_INITIAL_VALUE PIN_FLOATING
#define PB6_INITIAL_VALUE PIN_FLOATING
#define PB7_INITIAL_VALUE PIN_FLOATING

#define PC0_INITIAL_VALUE PIN_FLOATING
#define PC1_INITIAL_VALUE PIN_FLOATING
#define PC2_INITIAL_VALUE PIN_FLOATING
#define PC3_INITIAL_VALUE PIN_FLOATING
#define PC4_INITIAL_VALUE PIN_FLOATING
#define PC5_INITIAL_VALUE PIN_FLOATING
#define PC6_INITIAL_VALUE PIN_FLOATING
#define PC7_INITIAL_VALUE PIN_FLOATING

#define PD0_INITIAL_VALUE PIN_SET
#define PD1_INITIAL_VALUE PIN_SET
#define PD2_INITIAL_VALUE PIN_PULL_UP
#define PD3_INITIAL_VALUE PIN_SET
#define PD4_INITIAL_VALUE PIN_PULL_UP
#define PD5_INITIAL_VALUE PIN_PULL_UP
#define PD6_INITIAL_VALUE PIN_PULL_UP
#define PD7_INITIAL_VALUE PIN_PULL_UP



#endif /* DIO_Config_H_ */
